services:

  airflow-postgres:
    image: postgres:16
    container_name: airflow-postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    ports:
      - "5434:5432"

    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

  airflow-init:

    image: apache/airflow:2.9.2

    container_name: airflow-init

    depends_on:

      - airflow-postgres

    environment:

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow

    command: airflow db init

  airflow-webserver:
    image: apache/airflow:2.9.2

    container_name: airflow-webserver

    depends_on:
      - airflow-postgres

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow

    ports:
      - "8080:8080"

    volumes:
      - ../:/project
      - ./dags:/opt/airflow/dags

    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.2

    container_name: airflow-scheduler

    depends_on:
      - airflow-postgres

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow

    volumes: 
      - ../:/project
      - ./dags:/opt/airflow/dags

    command: scheduler

volumes:
  airflow_postgres_data: